# Playbook for update server and install tree package.
---
- name: package module example
  hosts: all
  become: true
  tasks:
    - name: 
      package:
        - name: tree 
          state: latest
          update_cache: yes 
      when: ansible_os_family == "Debian"
...