# Playbook for update server and install tree package.
---
- name: 
  hosts: all
  become: true
  tasks:
      package:
        - name: apache2
          state: latest
          update_cache: yes 
      when: ansible_os_family == "Debian"
...