---
- name: Installtion and update the node server
  hosts: all
  become: true
  tasks:
    - name: Updating node server and installing tree package at node server.
      package:
          state: latest
          update_cache: yes 
      when: ansible_os_family == "Debian"
...
# Playbook for update server and install tree package.