---
- name: Getting multiple factors
  hosts: all
  become: true
  tasks:
    - name: Getting ansible arcitecture
      debug:
        msg: "{{ansible_architecture}}"
    - name: Getting asible bios date
      debug: 
        msg: "{{ansible_bios_date}}"
    - name: getting ansible creation date and time
      debug:
        msg: "{{ansible_date_time}}"
    - name: Getting ansible bios vendor
      debug:
        msg: "{{ansible_domain}}"
        
...