---
- name: This shell module example
  hosts: all
  become: true
  tasks:
    - shell: echo "Hello Team" >> /mnt/abhishek.txt
    - name: creating text file with some content
      debug: 
        msg: check that file is created or not at node server at path /mnt/abhishek.txt

... 
