---
- name: This is second example of shell module
  hosts: all
  become: true
  tasks: 
    - shell: mkdir /abhishek && touch /abhishek/file1.txt
    - name: Making dir and file 
      debug:
        msg: Please check that dir and file is created or not at node server at given path.
...